version: 1.0.{build}

image: Visual Studio 2019 Preview

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

before_build:
  - nuget restore CommandContext\CommandContext.sln

build:
  project: CommandContext\CommandContext.sln

after_test:
  - ps: .\.nuget\pack.ps1

artifacts:
  - path: '**\CommandContext*.nupkg'
    name: CommandContext.nupkg

deploy:
  provider: NuGet
  api_key:
    secure: rw673hxHFWlGTxZ4b1QwYIDSktbZLJITclwBP8dVwB3XLGSf4wyLGmKKjHxSljNX
  artifact: CommandContext.nupkg
  